package carvajal.autenticador.android.dal.greendao.read;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CENSO.
 */
public class Censo {

    /** Not-null value. */
    private String Cedula;
    /** Not-null value. */
    private String PriApellido;
    private String SegApellido;
    /** Not-null value. */
    private String PriNombre;
    private String SegNombre;
    private int Sexo;
    /** Not-null value. */
    private String FecExpedicion;
    /** Not-null value. */
    private String CodProv;
    /** Not-null value. */
    private String CodMpio;
    /** Not-null value. */
    private String CodZona;
    /** Not-null value. */
    private String CodColElec;
    /** Not-null value. */
    private String CodMesa;
    private int TipoElector;
    private int ElectorImpedido;
    /** Not-null value. */
    private byte[] Foto;

    public Censo() {
    }

    public Censo(String Cedula) {
        this.Cedula = Cedula;
    }

    public Censo(String Cedula, String PriApellido, String SegApellido, String PriNombre, String SegNombre, int Sexo, String FecExpedicion, String CodProv, String CodMpio, String CodZona, String CodColElec, String CodMesa, int TipoElector, int ElectorImpedido, byte[] Foto) {
        this.Cedula = Cedula;
        this.PriApellido = PriApellido;
        this.SegApellido = SegApellido;
        this.PriNombre = PriNombre;
        this.SegNombre = SegNombre;
        this.Sexo = Sexo;
        this.FecExpedicion = FecExpedicion;
        this.CodProv = CodProv;
        this.CodMpio = CodMpio;
        this.CodZona = CodZona;
        this.CodColElec = CodColElec;
        this.CodMesa = CodMesa;
        this.TipoElector = TipoElector;
        this.ElectorImpedido = ElectorImpedido;
        this.Foto = Foto;
    }

    /** Not-null value. */
    public String getCedula() {
        return Cedula;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCedula(String Cedula) {
        this.Cedula = Cedula;
    }

    /** Not-null value. */
    public String getPriApellido() {
        return PriApellido;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPriApellido(String PriApellido) {
        this.PriApellido = PriApellido;
    }

    public String getSegApellido() {
        return SegApellido;
    }

    public void setSegApellido(String SegApellido) {
        this.SegApellido = SegApellido;
    }

    /** Not-null value. */
    public String getPriNombre() {
        return PriNombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPriNombre(String PriNombre) {
        this.PriNombre = PriNombre;
    }

    public String getSegNombre() {
        return SegNombre;
    }

    public void setSegNombre(String SegNombre) {
        this.SegNombre = SegNombre;
    }

    public int getSexo() {
        return Sexo;
    }

    public void setSexo(int Sexo) {
        this.Sexo = Sexo;
    }

    /** Not-null value. */
    public String getFecExpedicion() {
        return FecExpedicion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFecExpedicion(String FecExpedicion) {
        this.FecExpedicion = FecExpedicion;
    }

    /** Not-null value. */
    public String getCodProv() {
        return CodProv;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodProv(String CodProv) {
        this.CodProv = CodProv;
    }

    /** Not-null value. */
    public String getCodMpio() {
        return CodMpio;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodMpio(String CodMpio) {
        this.CodMpio = CodMpio;
    }

    /** Not-null value. */
    public String getCodZona() {
        return CodZona;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodZona(String CodZona) {
        this.CodZona = CodZona;
    }

    /** Not-null value. */
    public String getCodColElec() {
        return CodColElec;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodColElec(String CodColElec) {
        this.CodColElec = CodColElec;
    }

    /** Not-null value. */
    public String getCodMesa() {
        return CodMesa;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodMesa(String CodMesa) {
        this.CodMesa = CodMesa;
    }

    public int getTipoElector() {
        return TipoElector;
    }

    public void setTipoElector(int TipoElector) {
        this.TipoElector = TipoElector;
    }

    public int getElectorImpedido() {
        return ElectorImpedido;
    }

    public void setElectorImpedido(int ElectorImpedido) {
        this.ElectorImpedido = ElectorImpedido;
    }

    /** Not-null value. */
    public byte[] getFoto() {
        return Foto;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFoto(byte[] Foto) {
        this.Foto = Foto;
    }

}
