package carvajal.autenticador.android.dal.greendao.read;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import carvajal.autenticador.android.dal.greendao.read.Censo;
import carvajal.autenticador.android.dal.greendao.read.Templates;
import carvajal.autenticador.android.dal.greendao.read.Configuracion;
import carvajal.autenticador.android.dal.greendao.read.Provincias;
import carvajal.autenticador.android.dal.greendao.read.Municipios;
import carvajal.autenticador.android.dal.greendao.read.ColegiosElectorales;
import carvajal.autenticador.android.dal.greendao.read.Mesas;
import carvajal.autenticador.android.dal.greendao.read.Parametros;

import carvajal.autenticador.android.dal.greendao.read.CensoDao;
import carvajal.autenticador.android.dal.greendao.read.TemplatesDao;
import carvajal.autenticador.android.dal.greendao.read.ConfiguracionDao;
import carvajal.autenticador.android.dal.greendao.read.ProvinciasDao;
import carvajal.autenticador.android.dal.greendao.read.MunicipiosDao;
import carvajal.autenticador.android.dal.greendao.read.ColegiosElectoralesDao;
import carvajal.autenticador.android.dal.greendao.read.MesasDao;
import carvajal.autenticador.android.dal.greendao.read.ParametrosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig censoDaoConfig;
    private final DaoConfig templatesDaoConfig;
    private final DaoConfig configuracionDaoConfig;
    private final DaoConfig provinciasDaoConfig;
    private final DaoConfig municipiosDaoConfig;
    private final DaoConfig colegiosElectoralesDaoConfig;
    private final DaoConfig mesasDaoConfig;
    private final DaoConfig parametrosDaoConfig;

    private final CensoDao censoDao;
    private final TemplatesDao templatesDao;
    private final ConfiguracionDao configuracionDao;
    private final ProvinciasDao provinciasDao;
    private final MunicipiosDao municipiosDao;
    private final ColegiosElectoralesDao colegiosElectoralesDao;
    private final MesasDao mesasDao;
    private final ParametrosDao parametrosDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        censoDaoConfig = daoConfigMap.get(CensoDao.class).clone();
        censoDaoConfig.initIdentityScope(type);

        templatesDaoConfig = daoConfigMap.get(TemplatesDao.class).clone();
        templatesDaoConfig.initIdentityScope(type);

        configuracionDaoConfig = daoConfigMap.get(ConfiguracionDao.class).clone();
        configuracionDaoConfig.initIdentityScope(type);

        provinciasDaoConfig = daoConfigMap.get(ProvinciasDao.class).clone();
        provinciasDaoConfig.initIdentityScope(type);

        municipiosDaoConfig = daoConfigMap.get(MunicipiosDao.class).clone();
        municipiosDaoConfig.initIdentityScope(type);

        colegiosElectoralesDaoConfig = daoConfigMap.get(ColegiosElectoralesDao.class).clone();
        colegiosElectoralesDaoConfig.initIdentityScope(type);

        mesasDaoConfig = daoConfigMap.get(MesasDao.class).clone();
        mesasDaoConfig.initIdentityScope(type);

        parametrosDaoConfig = daoConfigMap.get(ParametrosDao.class).clone();
        parametrosDaoConfig.initIdentityScope(type);

        censoDao = new CensoDao(censoDaoConfig, this);
        templatesDao = new TemplatesDao(templatesDaoConfig, this);
        configuracionDao = new ConfiguracionDao(configuracionDaoConfig, this);
        provinciasDao = new ProvinciasDao(provinciasDaoConfig, this);
        municipiosDao = new MunicipiosDao(municipiosDaoConfig, this);
        colegiosElectoralesDao = new ColegiosElectoralesDao(colegiosElectoralesDaoConfig, this);
        mesasDao = new MesasDao(mesasDaoConfig, this);
        parametrosDao = new ParametrosDao(parametrosDaoConfig, this);

        registerDao(Censo.class, censoDao);
        registerDao(Templates.class, templatesDao);
        registerDao(Configuracion.class, configuracionDao);
        registerDao(Provincias.class, provinciasDao);
        registerDao(Municipios.class, municipiosDao);
        registerDao(ColegiosElectorales.class, colegiosElectoralesDao);
        registerDao(Mesas.class, mesasDao);
        registerDao(Parametros.class, parametrosDao);
    }
    
    public void clear() {
        censoDaoConfig.getIdentityScope().clear();
        templatesDaoConfig.getIdentityScope().clear();
        configuracionDaoConfig.getIdentityScope().clear();
        provinciasDaoConfig.getIdentityScope().clear();
        municipiosDaoConfig.getIdentityScope().clear();
        colegiosElectoralesDaoConfig.getIdentityScope().clear();
        mesasDaoConfig.getIdentityScope().clear();
        parametrosDaoConfig.getIdentityScope().clear();
    }

    public CensoDao getCensoDao() {
        return censoDao;
    }

    public TemplatesDao getTemplatesDao() {
        return templatesDao;
    }

    public ConfiguracionDao getConfiguracionDao() {
        return configuracionDao;
    }

    public ProvinciasDao getProvinciasDao() {
        return provinciasDao;
    }

    public MunicipiosDao getMunicipiosDao() {
        return municipiosDao;
    }

    public ColegiosElectoralesDao getColegiosElectoralesDao() {
        return colegiosElectoralesDao;
    }

    public MesasDao getMesasDao() {
        return mesasDao;
    }

    public ParametrosDao getParametrosDao() {
        return parametrosDao;
    }

}
