package carvajal.autenticador.android.dal.greendao.read;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MUNICIPIOS.
 */
public class Municipios {

    private Long id;
    /** Not-null value. */
    private String CodProv;
    /** Not-null value. */
    private String CodMpio;
    /** Not-null value. */
    private String NomMpio;

    public Municipios() {
    }

    public Municipios(Long id) {
        this.id = id;
    }

    public Municipios(Long id, String CodProv, String CodMpio, String NomMpio) {
        this.id = id;
        this.CodProv = CodProv;
        this.CodMpio = CodMpio;
        this.NomMpio = NomMpio;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCodProv() {
        return CodProv;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodProv(String CodProv) {
        this.CodProv = CodProv;
    }

    /** Not-null value. */
    public String getCodMpio() {
        return CodMpio;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCodMpio(String CodMpio) {
        this.CodMpio = CodMpio;
    }

    /** Not-null value. */
    public String getNomMpio() {
        return NomMpio;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNomMpio(String NomMpio) {
        this.NomMpio = NomMpio;
    }

}
