package carvajal.autenticador.android.dal.greendao.read;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PARAMETROS.
 */
public class Parametros {

    private Long id;
    private String NomParam;
    private String ValParam;

    public Parametros() {
    }

    public Parametros(Long id) {
        this.id = id;
    }

    public Parametros(Long id, String NomParam, String ValParam) {
        this.id = id;
        this.NomParam = NomParam;
        this.ValParam = ValParam;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNomParam() {
        return NomParam;
    }

    public void setNomParam(String NomParam) {
        this.NomParam = NomParam;
    }

    public String getValParam() {
        return ValParam;
    }

    public void setValParam(String ValParam) {
        this.ValParam = ValParam;
    }

}
