package carvajal.autenticador.android.dal.greendao.read;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import carvajal.autenticador.android.dal.greendao.read.Parametros;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PARAMETROS.
*/
public class ParametrosDao extends AbstractDao<Parametros, Long> {

    public static final String TABLENAME = "PARAMETROS";

    /**
     * Properties of entity Parametros.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NomParam = new Property(1, String.class, "NomParam", false, "NOM_PARAM");
        public final static Property ValParam = new Property(2, String.class, "ValParam", false, "VAL_PARAM");
    };


    public ParametrosDao(DaoConfig config) {
        super(config);
    }
    
    public ParametrosDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PARAMETROS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NOM_PARAM' TEXT," + // 1: NomParam
                "'VAL_PARAM' TEXT);"); // 2: ValParam
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PARAMETROS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Parametros entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String NomParam = entity.getNomParam();
        if (NomParam != null) {
            stmt.bindString(2, NomParam);
        }
 
        String ValParam = entity.getValParam();
        if (ValParam != null) {
            stmt.bindString(3, ValParam);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Parametros readEntity(Cursor cursor, int offset) {
        Parametros entity = new Parametros( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // NomParam
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // ValParam
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Parametros entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNomParam(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setValParam(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Parametros entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Parametros entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
