package carvajal.autenticador.android.dal.greendao.read;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import carvajal.autenticador.android.dal.greendao.read.Provincias;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PROVINCIAS.
*/
public class ProvinciasDao extends AbstractDao<Provincias, String> {

    public static final String TABLENAME = "PROVINCIAS";

    /**
     * Properties of entity Provincias.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property CodProv = new Property(0, String.class, "CodProv", true, "COD_PROV");
        public final static Property NomProv = new Property(1, String.class, "NomProv", false, "NOM_PROV");
    };


    public ProvinciasDao(DaoConfig config) {
        super(config);
    }
    
    public ProvinciasDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PROVINCIAS' (" + //
                "'COD_PROV' TEXT PRIMARY KEY NOT NULL ," + // 0: CodProv
                "'NOM_PROV' TEXT NOT NULL );"); // 1: NomProv
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PROVINCIAS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Provincias entity) {
        stmt.clearBindings();
 
        String CodProv = entity.getCodProv();
        if (CodProv != null) {
            stmt.bindString(1, CodProv);
        }
        stmt.bindString(2, entity.getNomProv());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Provincias readEntity(Cursor cursor, int offset) {
        Provincias entity = new Provincias( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // CodProv
            cursor.getString(offset + 1) // NomProv
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Provincias entity, int offset) {
        entity.setCodProv(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNomProv(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Provincias entity, long rowId) {
        return entity.getCodProv();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Provincias entity) {
        if(entity != null) {
            return entity.getCodProv();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
