package carvajal.autenticador.android.dal.greendao.read;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PROVINCIAS.
 */
public class Provincias {

    private String CodProv;
    /** Not-null value. */
    private String NomProv;

    public Provincias() {
    }

    public Provincias(String CodProv) {
        this.CodProv = CodProv;
    }

    public Provincias(String CodProv, String NomProv) {
        this.CodProv = CodProv;
        this.NomProv = NomProv;
    }

    public String getCodProv() {
        return CodProv;
    }

    public void setCodProv(String CodProv) {
        this.CodProv = CodProv;
    }

    /** Not-null value. */
    public String getNomProv() {
        return NomProv;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNomProv(String NomProv) {
        this.NomProv = NomProv;
    }

}
