package carvajal.autenticador.android.dal.greendao.read;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEMPLATES.
 */
public class Templates {

    /** Not-null value. */
    private String Cedula;
    private byte[] Template1;
    private byte[] Template2;
    private byte[] Template3;
    private byte[] Template4;
    private byte[] Template5;
    private byte[] Template6;
    private byte[] Template7;
    private byte[] Template8;
    private byte[] Template9;
    private byte[] Template10;

    public Templates() {
    }

    public Templates(String Cedula) {
        this.Cedula = Cedula;
    }

    public Templates(String Cedula, byte[] Template1, byte[] Template2, byte[] Template3, byte[] Template4, byte[] Template5, byte[] Template6, byte[] Template7, byte[] Template8, byte[] Template9, byte[] Template10) {
        this.Cedula = Cedula;
        this.Template1 = Template1;
        this.Template2 = Template2;
        this.Template3 = Template3;
        this.Template4 = Template4;
        this.Template5 = Template5;
        this.Template6 = Template6;
        this.Template7 = Template7;
        this.Template8 = Template8;
        this.Template9 = Template9;
        this.Template10 = Template10;
    }

    /** Not-null value. */
    public String getCedula() {
        return Cedula;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCedula(String Cedula) {
        this.Cedula = Cedula;
    }

    public byte[] getTemplate1() {
        return Template1;
    }

    public void setTemplate1(byte[] Template1) {
        this.Template1 = Template1;
    }

    public byte[] getTemplate2() {
        return Template2;
    }

    public void setTemplate2(byte[] Template2) {
        this.Template2 = Template2;
    }

    public byte[] getTemplate3() {
        return Template3;
    }

    public void setTemplate3(byte[] Template3) {
        this.Template3 = Template3;
    }

    public byte[] getTemplate4() {
        return Template4;
    }

    public void setTemplate4(byte[] Template4) {
        this.Template4 = Template4;
    }

    public byte[] getTemplate5() {
        return Template5;
    }

    public void setTemplate5(byte[] Template5) {
        this.Template5 = Template5;
    }

    public byte[] getTemplate6() {
        return Template6;
    }

    public void setTemplate6(byte[] Template6) {
        this.Template6 = Template6;
    }

    public byte[] getTemplate7() {
        return Template7;
    }

    public void setTemplate7(byte[] Template7) {
        this.Template7 = Template7;
    }

    public byte[] getTemplate8() {
        return Template8;
    }

    public void setTemplate8(byte[] Template8) {
        this.Template8 = Template8;
    }

    public byte[] getTemplate9() {
        return Template9;
    }

    public void setTemplate9(byte[] Template9) {
        this.Template9 = Template9;
    }

    public byte[] getTemplate10() {
        return Template10;
    }

    public void setTemplate10(byte[] Template10) {
        this.Template10 = Template10;
    }

}
