package carvajal.autenticador.android.dal.greendao.write;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import carvajal.autenticador.android.dal.greendao.write.Novedades;

import carvajal.autenticador.android.dal.greendao.write.NovedadesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig novedadesDaoConfig;

    private final NovedadesDao novedadesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        novedadesDaoConfig = daoConfigMap.get(NovedadesDao.class).clone();
        novedadesDaoConfig.initIdentityScope(type);

        novedadesDao = new NovedadesDao(novedadesDaoConfig, this);

        registerDao(Novedades.class, novedadesDao);
    }
    
    public void clear() {
        novedadesDaoConfig.getIdentityScope().clear();
    }

    public NovedadesDao getNovedadesDao() {
        return novedadesDao;
    }

}
