package carvajal.autenticador.android.dal.greendao.write;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOVEDADES.
 */
public class Novedades {

    private Long id;
    /** Not-null value. */
    private String TipoNovedad;
    /** Not-null value. */
    private String Cedula;
    private String CodProv;
    private String CodMpio;
    private String CodZona;
    private String CodColElec;
    private String CodMesa;
    /** Not-null value. */
    private String FechaNovedad;
    private String TipoElector;
    private String TemplateHit;
    /** Not-null value. */
    private String AndroidId;
    private String Score;
    private String CodProvConf;
    private String CodMpioConf;
    private String CodZonaConf;
    private String CodColElecConf;
    private String CodMesaConf;
    private String Sync;

    public Novedades() {
    }

    public Novedades(Long id) {
        this.id = id;
    }

    public Novedades(Long id, String TipoNovedad, String Cedula, String CodProv, String CodMpio, String CodZona, String CodColElec, String CodMesa, String FechaNovedad, String TipoElector, String TemplateHit, String AndroidId, String Score, String CodProvConf, String CodMpioConf, String CodZonaConf, String CodColElecConf, String CodMesaConf, String Sync) {
        this.id = id;
        this.TipoNovedad = TipoNovedad;
        this.Cedula = Cedula;
        this.CodProv = CodProv;
        this.CodMpio = CodMpio;
        this.CodZona = CodZona;
        this.CodColElec = CodColElec;
        this.CodMesa = CodMesa;
        this.FechaNovedad = FechaNovedad;
        this.TipoElector = TipoElector;
        this.TemplateHit = TemplateHit;
        this.AndroidId = AndroidId;
        this.Score = Score;
        this.CodProvConf = CodProvConf;
        this.CodMpioConf = CodMpioConf;
        this.CodZonaConf = CodZonaConf;
        this.CodColElecConf = CodColElecConf;
        this.CodMesaConf = CodMesaConf;
        this.Sync = Sync;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTipoNovedad() {
        return TipoNovedad;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTipoNovedad(String TipoNovedad) {
        this.TipoNovedad = TipoNovedad;
    }

    /** Not-null value. */
    public String getCedula() {
        return Cedula;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCedula(String Cedula) {
        this.Cedula = Cedula;
    }

    public String getCodProv() {
        return CodProv;
    }

    public void setCodProv(String CodProv) {
        this.CodProv = CodProv;
    }

    public String getCodMpio() {
        return CodMpio;
    }

    public void setCodMpio(String CodMpio) {
        this.CodMpio = CodMpio;
    }

    public String getCodZona() {
        return CodZona;
    }

    public void setCodZona(String CodZona) {
        this.CodZona = CodZona;
    }

    public String getCodColElec() {
        return CodColElec;
    }

    public void setCodColElec(String CodColElec) {
        this.CodColElec = CodColElec;
    }

    public String getCodMesa() {
        return CodMesa;
    }

    public void setCodMesa(String CodMesa) {
        this.CodMesa = CodMesa;
    }

    /** Not-null value. */
    public String getFechaNovedad() {
        return FechaNovedad;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaNovedad(String FechaNovedad) {
        this.FechaNovedad = FechaNovedad;
    }

    public String getTipoElector() {
        return TipoElector;
    }

    public void setTipoElector(String TipoElector) {
        this.TipoElector = TipoElector;
    }

    public String getTemplateHit() {
        return TemplateHit;
    }

    public void setTemplateHit(String TemplateHit) {
        this.TemplateHit = TemplateHit;
    }

    /** Not-null value. */
    public String getAndroidId() {
        return AndroidId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAndroidId(String AndroidId) {
        this.AndroidId = AndroidId;
    }

    public String getScore() {
        return Score;
    }

    public void setScore(String Score) {
        this.Score = Score;
    }

    public String getCodProvConf() {
        return CodProvConf;
    }

    public void setCodProvConf(String CodProvConf) {
        this.CodProvConf = CodProvConf;
    }

    public String getCodMpioConf() {
        return CodMpioConf;
    }

    public void setCodMpioConf(String CodMpioConf) {
        this.CodMpioConf = CodMpioConf;
    }

    public String getCodZonaConf() {
        return CodZonaConf;
    }

    public void setCodZonaConf(String CodZonaConf) {
        this.CodZonaConf = CodZonaConf;
    }

    public String getCodColElecConf() {
        return CodColElecConf;
    }

    public void setCodColElecConf(String CodColElecConf) {
        this.CodColElecConf = CodColElecConf;
    }

    public String getCodMesaConf() {
        return CodMesaConf;
    }

    public void setCodMesaConf(String CodMesaConf) {
        this.CodMesaConf = CodMesaConf;
    }

    public String getSync() {
        return Sync;
    }

    public void setSync(String Sync) {
        this.Sync = Sync;
    }

}
